### ISSUE TITLE
sanitizer ASAN build failures

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#112]
The travis `TOOLSET=asan` builds are failing https://travis-ci.org/mapbox/vtquery/jobs/589055268 with the following errors:

```
$ npm test
> @mapbox/vtquery@0.3.1-basic-filter test /home/travis/build/mapbox/vtquery
> UV_THREADPOOL_SIZE=1 tape test/*.test.js
internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: /home/travis/build/mapbox/vtquery/lib/binding/vtquery.node: undefined symbol: __asan_report_store4
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/travis/build/mapbox/vtquery/lib/index.js:39:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
cache.2
store build cache
```

Originally discovered in #110, but the builds are also failing on master. @CyanRook noted: 

> Asan might just be broken until https://github.com/nodejs/build/issues/1906 is fixed by https://github.com/nodejs/node/pull/29383 

cc @mapbox/tilesets-api @CyanRook

**Comment by springmeyer** [comment]
Taking a look now

**Comment by springmeyer** [comment]
Working on a fix over at https://github.com/mapbox/vtquery/pull/114

**Comment by springmeyer** [comment]
Fixed now by https://github.com/mapbox/vtquery/pull/114

**Comment by mapsam** [comment]
Thanks @springmeyer!
